### PR TITLE
basic port to 1.20.4 for fabric

### PR DESCRIPTION
**Pull request by petersv5**
This basic port to 1.20.4 seems to work for at least our basic use. It has received very light testing so far.

### CODE REVIEW

**Comment by petersv5** [comment]
There are several errors from FogreConfigPort during server shutdown.

**Comment by Z0rdak** [comment]
I just ported this version again, after the version pulished turned out to be broken due to the config not working properly. 
The latest fabric and Forge Config API Port versions seem to work fine.

I thank you very much for your effort.

**Comment by petersv5** [comment]
I'm sorry for messing up. We only performed very limited testing for the functions that are used on our own servers, and that is really really basic. I should have pointed out the very limited testing, that is definitly on me.

**Comment by Z0rdak** [comment]
Don’t be sorry. You clearly pointed this out.
I think it rather was a combination of the beta state of fabric and the mod at this point.

Now with more mature, fixed version it just ran fine.

**Pull request closed without merging**
